[versions]
dokka = "1.9.20"
junit-jupiter = "5.11.0"
kotlin = "2.1.0"
kotlinx-serialization-core = "1.7.3"
nexus-publish = "0.4.0"
nexus-staging = "0.30.0"
researchgate-release = "3.0.2"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization-core" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-publish = { id = "de.marcphilipp.nexus-publish", version.ref = "nexus-publish" }
nexus-staging = { id = "io.codearte.nexus-staging", version.ref = "nexus-staging" }
researchgate-release = { id = "net.researchgate.release", version.ref = "researchgate-release" }
